apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-app
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tasky

  template:
    metadata:
      labels:
        app: tasky

    spec:
      serviceAccountName: cluster-admin-sa

      containers:
      - name: tasky

        image: 886436966911.dkr.ecr.us-east-2.amazonaws.com/tasky:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: MONGODB_URI
          value: "mongodb://wizuser:wizpassword@REPLACE_MONGO_PRIVATE_IP:27017/tasky?authSource=tasky"
