name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::886436966911:role/github-actions-role
          aws-region: us-east-2

      - name: Deploy Network
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/network.yaml \
          --stack-name network \
          --region us-east-2

      - name: Deploy Security IAM
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/02-security.yaml \
          --stack-name security-iam \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-2

      - name: Deploy Storage
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/storage.yaml \
          --stack-name storage \
          --region us-east-2

      - name: Deploy MongoDB
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/mongodb-ec2.yaml \
          --stack-name mongodb \
          --region us-east-2

      - name: Deploy ECR
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/ecr.yaml \
          --stack-name ecr \
          --region us-east-2

      - name: Deploy EKS
        run: |
          aws cloudformation deploy \
          --template-file cloudformation/EKS.yaml \
          --stack-name eks \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-2
